volumes:
  dev_postgres_data: {}
  dev_postgres_data_backups: {}
  dev_traefik: {}
  {%- if cookiecutter.cloud_provider == 'None' %}
  dev_django_media: {}
  {%- endif %}
  {% if cookiecutter.use_celery == 'y' %}
  dev_redis_data: {}
  {% endif %}


services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile

    image: {{ cookiecutter.project_slug }}_dev_django
    {%- if cookiecutter.cloud_provider == 'None' %}
    volumes:
      - dev_django_media:/app/{{ cookiecutter.project_slug }}/media
    {%- endif %}
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.dev/.django
      - ./.envs/.dev/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: {{ cookiecutter.project_slug }}_dev_postgres
    volumes:
      {%- if cookiecutter.postgresql_version|int >= 18 %}
      - dev_postgres_data:/var/lib/postgresql/{{ cookiecutter.postgresql_version }}/docker
      {%- else %}
      - dev_postgres_data:/var/lib/postgresql/data
      {%- endif %}
      - dev_postgres_data_backups:/backups
    env_file:
      - ./.envs/.dev/.postgres

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
      args:
        ENVIRONMENT: dev
    image: {{ cookiecutter.project_slug }}_dev_traefik
    depends_on:
      - django
    volumes:
      - dev_traefik:/etc/traefik/acme
    ports:
      - '0.0.0.0:80:80'
      - '0.0.0.0:443:443'
      {%- if cookiecutter.use_celery == 'y' %}
      - '0.0.0.0:5555:5555'
      {%- endif %}

  redis:
    image: docker.io/redis:7.2
    {% if cookiecutter.use_celery == 'y' %}
    volumes:
      - dev_redis_data:/data
    {% endif %}

  taskworker:
    <<: *django
    image: {{ cookiecutter.project_slug }}_dev_taskworker
    command: /start-taskworker


  {%- if cookiecutter.use_celery == 'y' %}

  celeryworker:
    <<: *django
    image: {{ cookiecutter.project_slug }}_dev_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: {{ cookiecutter.project_slug }}_dev_celerybeat
    command: /start-celerybeat

  flower:
    <<: *django
    image: {{ cookiecutter.project_slug }}_dev_flower
    command: /start-flower
  {%- endif %}
  {%- if cookiecutter.cloud_provider == 'AWS' %}

  awscli:
    build:
      context: .
      dockerfile: ./compose/production/aws/Dockerfile
    env_file:
      - ./.envs/.dev/.django
    volumes:
      - dev_postgres_data_backups:/backups:z
  {%- endif %}
  {%- if cookiecutter.cloud_provider == 'None' %}

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: {{ cookiecutter.project_slug }}_dev_nginx
    depends_on:
      - django
    volumes:
      - dev_django_media:/usr/share/nginx/media:ro
  {%- endif %}
