release: python manage.py migrate
web: gunicorn config.asgi:application -k uvicorn_worker.UvicornWorker
taskworker: python manage.py db_worker
{%- if cookiecutter.use_celery == "y" %}
worker: REMAP_SIGTERM=SIGQUIT celery -A config.celery_app worker --loglevel=info
beat: REMAP_SIGTERM=SIGQUIT celery -A config.celery_app beat --loglevel=info
{%- endif %}
