# The routers of the dev environment: the hosts it answers for. The services and
# middlewares they name are in ``shared.yml``.
http:
  routers:
    web-secure-router:
      rule: 'Host(`dev.{{ cookiecutter.domain_name }}`)'
      entryPoints:
        - web-secure
      middlewares:
        - csrf
      service: django
      tls:
        # https://doc.traefik.io/traefik/routing/routers/#certresolver
        certResolver: letsencrypt
    {%- if cookiecutter.use_celery == 'y' %}

    flower-secure-router:
      rule: 'Host(`dev.{{ cookiecutter.domain_name }}`)'
      entryPoints:
        - flower
      service: flower
      tls:
        # https://doc.traefik.io/traefik/master/routing/routers/#certresolver
        certResolver: letsencrypt
    {%- endif %}
    {%- if cookiecutter.cloud_provider == 'None' %}

    web-media-router:
      rule: 'Host(`dev.{{ cookiecutter.domain_name }}`) && PathPrefix(`/media/`)'
      entryPoints:
        - web-secure
      middlewares:
        - csrf
      service: django-media
      tls:
        certResolver: letsencrypt
    {%- endif %}
